/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KlijentskiZahtev;
import komunikacija.KomunikacijaSaServerom;
import komunikacija.ServerskiOdgovor;
import kontroler.Kontroler;
import operacije.Operacije;

/**
 *
 * @author User
 */
public class KlijentskaForma extends javax.swing.JFrame {

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        setTitle("Skola borilackih vestina - Klijentski program");
        setLocationRelativeTo(null);
        txtTrener.setEditable(false);
        txtTrener.setText(Kontroler.getInstance().getTrener().getIme() + " " + Kontroler.getInstance().getTrener().getPrezime());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTrener = new javax.swing.JTextField();
        btnKreirajPolaznika = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPretragaPolaznika = new javax.swing.JButton();
        btnKreirajKurs = new javax.swing.JButton();
        btnPregledKurseva = new javax.swing.JButton();
        btnPregledTreninga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Trener");

        btnKreirajPolaznika.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKreirajPolaznika.setText("Kreiraj novog polaznika");
        btnKreirajPolaznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajPolaznikaActionPerformed(evt);
            }
        });

        btnLogout.setText("Odjava");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnPretragaPolaznika.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPretragaPolaznika.setText("Pretrazi polaznike");
        btnPretragaPolaznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaPolaznikaActionPerformed(evt);
            }
        });

        btnKreirajKurs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKreirajKurs.setText("Kreiraj novi kurs");
        btnKreirajKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajKursActionPerformed(evt);
            }
        });

        btnPregledKurseva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPregledKurseva.setText("Pogledaj listu kurseva");
        btnPregledKurseva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledKursevaActionPerformed(evt);
            }
        });

        btnPregledTreninga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPregledTreninga.setText("Pregled zakazanih treninga");
        btnPregledTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledTreningaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(txtTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPretragaPolaznika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKreirajPolaznika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKreirajKurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPregledKurseva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPregledTreninga, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(34, 34, 34)
                .addComponent(btnKreirajPolaznika, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPretragaPolaznika, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKreirajKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPregledKurseva, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnPregledTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajPolaznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajPolaznikaActionPerformed
        KreiranjePolaznika kp = new KreiranjePolaznika();
        kp.setVisible(true);
    }//GEN-LAST:event_btnKreirajPolaznikaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        logout();
        System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnKreirajKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajKursActionPerformed
        KreiranjeKursa kk = new KreiranjeKursa();
        kk.setVisible(true);
    }//GEN-LAST:event_btnKreirajKursActionPerformed

    private void btnPregledKursevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledKursevaActionPerformed
        PregledListeKurseva plk = new PregledListeKurseva();
        plk.setVisible(true);
    }//GEN-LAST:event_btnPregledKursevaActionPerformed

    private void btnPretragaPolaznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaPolaznikaActionPerformed
        PretrazivanjePolaznika pp = new PretrazivanjePolaznika();
        pp.setVisible(true);
    }//GEN-LAST:event_btnPretragaPolaznikaActionPerformed

    private void btnPregledTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledTreningaActionPerformed
        PregledTreninga pt = new PregledTreninga();
        pt.setVisible(true);
    }//GEN-LAST:event_btnPregledTreningaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajKurs;
    private javax.swing.JButton btnKreirajPolaznika;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPregledKurseva;
    private javax.swing.JButton btnPregledTreninga;
    private javax.swing.JButton btnPretragaPolaznika;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtTrener;
    // End of variables declaration//GEN-END:variables

    private void logout(){
        try {
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.LOGOUT);
            kz.setParametar(Kontroler.getInstance().getTrener());
            
            KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().primiOdgovor();
            
            if(so.isUspesno()) {
                JOptionPane.showMessageDialog(this, so.getPoruka(), "Uspesno!", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this, so.getPoruka(), "Greska!", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (InterruptedException ex) {
            Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
